moma/config/routes.rb
Rails.application.routes.draw do
  root :to => 'artists#index'
  
  resources :artists, :works
end

moma/app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :integer          not null, primary key
#  name        :string
#  nationality :string
#  dob         :date
#  period      :string
#  image       :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Artist < ActiveRecord::Base
    has_many :works
end

moma/app/models/work.rb
# == Schema Information
#
# Table name: works
#
#  id         :integer          not null, primary key
#  title      :string
#  year       :string
#  medium     :string
#  style      :string
#  image      :text
#  created_at :datetime
#  updated_at :datetime
#  artist_id  :integer
#

class Work < ActiveRecord::Base
    belongs_to :artist
end

moma/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

moma/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def create
    artist = Artist.create artist_params
    redirect_to artist
  end

  def new
    @artist = Artist.new
  end

  def edit
    @artist = Artist.find params[:id]
  end

  def show
    @artist = Artist.find params[:id]
  end

  def update
    artist = Artist.find params[:id]
    artist.update artist_params
    redirect_to artist
  end

  def destroy
    artist = Artist.find params[:id]
    artist.destroy
    redirect_to artists_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :nationality, :dob, :period, :image)
  end
end

moma/app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all
  end

  def create
    work = Work.create work_params
    redirect_to work
  end

  def new
    @work = Work.new
  end

  def edit
    @work = Work.find params[:id]
  end

  def show
    @work = Work.find params[:id]
  end

  def update
    work = Work.find params[:id]
    work.update work_params
    redirect_to work
  end

  def destroy
    work = Work.find params[:id]
    work.destroy
    redirect_to works_path
  end

  private
  def work_params
    params.require(:work).permit(:title, :year, :medium, :style, :image, :artist_id)
  end
end

moma/app/helpers/application_helper.rb
module ApplicationHelper
end

moma/app/helpers/artists_helper.rb
module ArtistsHelper
end

moma/app/helpers/works_helper.rb
module WorksHelper
end

moma/app/views/works/_form.html.erb
<%= form_for @work do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title, :autofocus => true %>

    <%= f.label :year %>
    <%= f.text_field :year %>

    <%= f.label :medium %>
    <%= f.text_field :medium %>

    <%= f.label :style %>
    <%= f.text_field :style %>

    <%= f.label :image %>
    <%= f.url_field :image %>
    <br>
    <%= f.label :artist_id %>
    <%= f.select :artist_id, Artist.all.map {|artist| [artist.name, artist.id]}, :include_blank => true %>

    <%= f.submit %>

<% end %>

moma/app/views/works/edit.html.erb
<h1>Edit Work</h1>
<%= render :partial => 'form' %>

moma/app/views/works/index.html.erb
<h1>Works</h1>
<% @works.each do |work| %>
    <%= link_to(image_tag(work.image, :class => 'thumb'), work) %>
    <ul>
        <li><%= work.title %></li>
        <li><%= work.year %></li>
        <li><%= work.medium %></li>
        <li><%= work.style %></li>
    </ul>
<% end %>

moma/app/views/works/new.html.erb
<h1>New Work</h1>
<%= render :partial => 'form' %>

moma/app/views/works/show.html.erb
<h1> <%= @work.title %></h1>
<%= link_to 'Delete work', @work, :method => 'delete',
            :data => {:confirm => "Are you sure?"} %>
<%= link_to 'Update work', edit_work_path(@work) %>
<ul>
    <% if @work.artist %>
    <li>Artist: <%= link_to(@work.artist.name, @work.artist) %></li>
    <% end %>
    <li>Year: <%= @work.year %></li>
    <li>Medium: <%= @work.medium %></li>
    <li>Style: <%= @work.style %></li>      
</ul>

<%= image_tag(@work.image, :class => 'work') %>

moma/app/views/works/update.html.erb
<h1>Works#update</h1>
<p>Find me in app/views/works/update.html.erb</p>